# Generated by Django 2.1.3 on 2018-11-11 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator('^[a-Z]+$', 'First name should only contain characters from a to z.')]),
        ),
    ]
