# Generated by Django 2.1.3 on 2018-11-11 02:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club_management', '0003_profile_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='second_name',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Second name must be made of characters only.')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'First name must be made of characters only.')]),
        ),
    ]
