# Generated by Django 2.1.1 on 2018-11-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0004_auto_20181110_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, help_text='Your own personalized description.'),
        ),
    ]
