# Generated by Django 2.1.1 on 2018-11-11 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0005_profile_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='self_description',
        ),
    ]
