# Generated by Django 2.1.3 on 2018-11-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0006_auto_20181111_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='self_description',
        ),
    ]
