# Generated by Django 2.1.3 on 2018-11-11 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0007_remove_profile_self_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='self_description',
            field=models.TextField(blank=True, null=True, verbose_name='self description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'First name must be made of characters only.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_name',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Second name must be made of characters only.')]),
        ),
    ]
