# Generated by Django 2.1.3 on 2018-11-11 15:12

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0008_auto_20181111_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clubs',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='club_management.Club', verbose_name='club'),
        ),
    ]
